import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        MT: {
          primary: "#ACC7FF",
          surfaceTint: "#ACC7FF",
          onPrimary: "#0F2F60",
          primaryContainer: "#2A4678",
          onPrimaryContainer: "#D7E2FF",
          secondary: "#DAC76F",
          onSecondary: "#393000",
          secondaryContainer: "#524600",
          onSecondaryContainer: "#F7E388",
          tertiary: "#DEBCDF",
          onTertiary: "#402844",
          tertiaryContainer: "#583E5B",
          onTertiaryContainer: "#FBD7FC",
          error: "#FFB4AB",
          onError: "#690005",
          errorContainer: "#93000A",
          onErrorContainer: "#FFDAD6",
          background: "#111318",
          onBackground: "#E2E2E9",
          surface: "#111318",
          onSurface: "#E2E2E9",
          surfaceVariant: "#44474F",
          onSurfaceVariant: "#C4C6D0",
          outline: "#8E9099",
          outlineVariant: "#44474F",
          shadow: "#000000",
          scrim: "#000000",
          inverseSurface: "#E2E2E9",
          inverseOnSurface: "#2F3036",
          inversePrimary: "#435E91",
          primaryFixed: "#D7E2FF",
          onPrimaryFixed: "#001A40",
          primaryFixedDim: "#ACC7FF",
          onPrimaryFixedVariant: "#2A4678",
          secondaryFixed: "#F7E388",
          onSecondaryFixed: "#211B00",
          secondaryFixedDim: "#DAC76F",
          onSecondaryFixedVariant: "#524600",
          tertiaryFixed: "#FBD7FC",
          onTertiaryFixed: "#29132D",
          tertiaryFixedDim: "#DEBCDF",
          onTertiaryFixedVariant: "#583E5B",
          surfaceDim: "#111318",
          surfaceBright: "#37393E",
          surfaceContainerLowest: "#0C0E13",
          surfaceContainerLow: "#1A1B20",
          surfaceContainer: "#1E2025",
          surfaceContainerHigh: "#282A2F",
          surfaceContainerHighest: "#33353A",
        },
      },
      backgroundImage: {
        "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
        "gradient-conic":
          "conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))",
      },
    },
  },
  plugins: [],
};
export default config;
